name: Update README.md

on:
  schedule:
    # Schedule the workflow to run every 6 months (January 1st and July 1st)
    - cron: "0 0 1 1,7 *"
  workflow_dispatch:  # Allow manual trigger
    inputs:
      force:
        description: 'Force update README.md'
        required: false
        default: 'false'

permissions:
  contents: write
  actions: none

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13'

      - name: Upgrade pip and setuptools
        run: |
          pip install --upgrade pip
          pip install --upgrade setuptools

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Audit dependencies
        run: pip install pip-audit && pip-audit

      - name: Execute update_readme.py
        run: python cogs/update_readme.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          # Check if there are any changes
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update README.md automatically"
            git push
          fi
